### PR TITLE
Update README.md with general documentation

### PR DESCRIPTION
**Pull request by tiangolo**
I added instructions on how to install and some usage examples.

### CODE REVIEW

**Comment by neerajdotname** [comment]
This PR should be merged.

**Comment by tance77** [comment]
I'm getting a node-gyp error when rebuilding for electron an suggestions @tiangolo

**Comment by tiangolo** [comment]
@tance77 it seems like there's something wrong with your `PATH`, maybe you can try uninstalling and reinstalling Node, and using the latest version (8 as of now).

Unfortunately, I'm not a `nvm` user, so I don't know how to help you with that.

**Comment by tance77** [comment]
@tiangolo I receive the same error, thanks for the reply though.

**Comment by fangzhzh** [comment]
For electron user, I also noticed the @paulcbetts/system-idle-time should be install under app folder

according to this link: https://github.com/chentsulin/electron-react-boilerplate/wiki/Module-Structure----Two-package.json-Structure#what-is-a-native-module

**Comment by cqernst** [comment]
@tiangolo thank you for these instructions! I am able to run the module in my main.js file, but even after a successful electron-rebuild I get this error when I try to require the module into a React component: 

Uncaught Error: Could not locate the bindings file. bindings.js:91. Tried:
[list of files it checked]
 at bindings (bindings.js:88)
    at Object../node_modules/@paulcbetts/system-idle-time/addon.js (addon.js:1)
    at __webpack_require__ (bootstrap:19)

This seems like a webpack issue - any thoughts?

**Comment by tiangolo** [comment]
This PR has been here waiting for a very long time. I'm currently not working on the app that I was building that used it.

But as the project seems abandoned, I had planned to try https://github.com/bithavoc/node-desktop-idle by @bithavoc (I still haven't).

I heard of it on this issue (in this same repo): https://github.com/paulcbetts/node-system-idle-time/issues/12

`node-system-idle-time` (this package) seems to be a fork and modification of some snippets from other places (you can infer it from the commit log messages). It helped a lot, but I think the author didn't intend to maintain it that much.

I understand that `node-desktop-idle` was built "from scratch" and with more intentions to be maintained. So, if I was to develop something using this feature, I would first try that package first and see if it works.

**Comment by fangzhzh** [comment]
@tiangolo I tried both. both works.

@cqernst  I met your problem before. I fixed it by following below steps.

```
$cd app
$yarn add @paulcbetts/system-idle-time
$cd ..
$./node_modules/.bin/electron-rebuild -m ./app/ -f
```

**Comment by bithavoc** [comment]
@tiangolo @fangzhzh that's correct, I'm currently maintaining https://github.com/bithavoc/node-desktop-idle for this purpose. No more memory leaks or running out of descriptors on Linux ;)

**Comment by tiangolo** [comment]
I'm not working on this anymore, for a long while. I'm currently cleaning up my forked repos, so I'm removing this branch and fork. I just wanted to leave this short message here before doing it. :nerd_face: :coffee:

**Pull request closed without merging**
